export const HEALTH={ok:true,service:'kukirin-leaderboard',apiVersion:1};
export const MODES=['drag','speed','delivery'];
export function validScore(row){return row&&typeof row.id==='string'&&/^[a-f0-9-]{36}$/i.test(row.id)&&typeof row.name==='string'&&row.name.trim().length>=2&&row.name.trim().length<=24&&typeof row.vehicle==='string'&&row.vehicle.length<=80&&Number.isFinite(row.value)&&MODES.includes(row.mode)&&row.value>0&&row.value<=(row.mode==='delivery'?1000000:row.mode==='speed'?1000:600)&&(row.mode!=='drag'||row.value>=2);}
export function scoreQuery(mode){return `SELECT MIN(id) id,name,vehicle,${mode==='drag'?'MIN':'MAX'}(value) value FROM scores WHERE mode=? GROUP BY name,vehicle ORDER BY value ${mode==='drag'?'ASC':'DESC'} LIMIT 50`;}
export const HOME=`<!doctype html><html lang="et"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KuKirin Tuner · Edetabel</title><style>body{background:#07111f;color:#e0f2fe;font:16px system-ui;margin:auto;padding:24px;max-width:760px}h1{font-size:28px}section{background:#102136;padding:20px;border:1px solid #31516c;border-radius:18px;margin:20px 0}input{box-sizing:border-box;width:100%;padding:14px;background:#07111f;color:#7dd3fc;border:1px solid #31516c;border-radius:10px}button{padding:12px;border:0;border-radius:10px;background:#159ce9;color:white;margin:10px 4px 0 0;min-height:44px}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #31516c;padding:12px 4px;overflow-wrap:anywhere}small,p{color:#a1b9cb}nav{display:flex;flex-wrap:wrap}button[aria-pressed=false]{background:#203347}</style><h1>KuKirin Tuner · Edetabel</h1><section><h2>Ühenda mäng selle serveriga</h2><p>Avaleht → Edetabel → Serveri aadress → Kontrolli ja ühenda.</p><label for="address">Serveri aadress</label><input id="address" readonly><button id="copy">Kopeeri aadress</button><p id="hint" role="status">Kõik mängijad kasutavad sama serveri aadressi.</p></section><nav><button data-mode="drag" aria-pressed="true">400 m drag</button><button data-mode="speed" aria-pressed="false">Tippkiirus</button><button data-mode="delivery" aria-pressed="false">Kulleritööd</button></nav><p id="status" role="status"></p><table><thead><tr><th>Nimi</th><th>Sõiduk</th><th>Tulemus</th></tr></thead><tbody id="rows"></tbody></table><script>
const address=document.getElementById('address');address.value=location.origin;
if(['localhost','127.0.0.1'].includes(location.hostname))document.getElementById('hint').textContent='See on selle arvuti testiserver. Kõigi mängijate jaoks paigalda server avalikule HTTPS-aadressile.';
document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(address.value);document.getElementById('copy').textContent='Kopeeritud';}catch{address.select();}};
let current='drag',version=0;async function load(mode){current=mode;const request=++version;document.querySelectorAll('[data-mode]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.mode===mode)));document.getElementById('status').textContent='Laadin…';document.getElementById('rows').replaceChildren();try{const response=await fetch('/scores?mode='+mode);if(!response.ok)throw Error();const rows=await response.json();if(request!==version)return;for(const row of rows){const tr=document.createElement('tr');for(const text of [row.name,row.vehicle,Number(row.value).toFixed(mode==='drag'?3:0)+(mode==='drag'?' s':mode==='speed'?' km/h':' €')]){const td=document.createElement('td');td.textContent=text;tr.append(td);}document.getElementById('rows').append(tr);}document.getElementById('status').textContent=rows.length?'':'Tulemusi veel pole.';}catch{if(request===version)document.getElementById('status').textContent='Server ei vasta. Proovi uuesti.';}}
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>load(button.dataset.mode));load(current);
</script></html>`;
