import {useEffect,useMemo,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Heart,MessageCircle,ArrowLeft,Plus,Volume2,VolumeX,Play,Pause,ChevronUp,ChevronDown,Trash2} from 'lucide-react';
import {useLanguage} from '../lib/i18n';
import {FEATURED_VIDEOS,loadFeedVideos,addFeedVideo,removeFeedVideo} from '../lib/feedVideos';
function readState(){try{return JSON.parse(localStorage.getItem('kukirin_feed_social')||'{}');}catch{return {};}}
function FeedVideo({post,active,muted,paused,onPause,onError}){
 const ref=useRef(null);
 useEffect(()=>{const v=ref.current;if(!v)return;if(active&&!paused&&!document.hidden)v.play().catch(()=>{});else v.pause();},[active,paused,post.src]);
 useEffect(()=>{const fn=()=>{const v=ref.current;if(document.hidden)v?.pause();else if(active&&!paused)v?.play().catch(()=>{});};document.addEventListener('visibilitychange',fn);return()=>document.removeEventListener('visibilitychange',fn);},[active,paused]);
 return <video ref={ref} src={post.src} poster={post.poster} loop playsInline muted={muted} preload={active?'auto':'metadata'} onClick={onPause} onError={onError} aria-label={post.name}/>;
}
export default function FanFeed(){
 const navigate=useNavigate();const {language}=useLanguage();const text=(en,et)=>language==='et'?et:en;
 const [localClips,setLocalClips]=useState([]),[active,setActive]=useState(FEATURED_VIDEOS[0].id),[muted,setMuted]=useState(true),[paused,setPaused]=useState(false),[social,setSocial]=useState(readState),[comments,setComments]=useState(null),[draft,setDraft]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const viewport=useRef(null),input=useRef(null);
 useEffect(()=>{let live=true;loadFeedVideos().then(clips=>{if(live)setLocalClips(clips.sort((a,b)=>b.created-a.created));}).catch(()=>{if(live)setNotice(text('Video storage could not be opened.','Videote salvestust ei saanud avada.'));});return()=>{live=false;};},[]);
 const uploads=useMemo(()=>localClips.map(clip=>({...clip,src:URL.createObjectURL(clip.blob),author:text('You','Sina')})),[localClips,language]);
 useEffect(()=>()=>uploads.forEach(clip=>URL.revokeObjectURL(clip.src)),[uploads]);
 const posts=[...FEATURED_VIDEOS.map(clip=>({...clip,name:text(clip.nameEn,clip.name)})),...uploads];
 useEffect(()=>{const root=viewport.current;if(!root)return;const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting&&e.intersectionRatio>.6).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible){setActive(visible.target.dataset.clip);setPaused(false);}}, {root,threshold:[.6,.8]});root.querySelectorAll('[data-clip]').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[localClips]);
 useEffect(()=>{localStorage.setItem('kukirin_feed_social',JSON.stringify(social));},[social]);
 useEffect(()=>{const fn=e=>{if(e.key==='Escape')setComments(null);};document.addEventListener('keydown',fn);return()=>document.removeEventListener('keydown',fn);},[]);
 function move(direction){const index=posts.findIndex(p=>p.id===active),next=posts[Math.max(0,Math.min(posts.length-1,index+direction))];viewport.current.querySelector(`[data-clip="${next.id}"]`)?.scrollIntoView({behavior:'smooth',block:'nearest'});}
 async function upload(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);try{const clip=await addFeedVideo(file);setLocalClips(prev=>[clip,...prev]);setNotice(text('Video saved on this device.','Video salvestati sellesse seadmesse.'));}catch(err){setNotice(err.message==='size'?text('Maximum video size is 100 MB.','Video võib olla kuni 100 MB.'):text('Could not save this video. Choose an MP4 or WebM file.','Videot ei saanud salvestada. Vali MP4 või WebM fail.'));}finally{setBusy(false);}}
 return <div className="video-feed">
  <header><button type="button" aria-label={text('Back','Tagasi')} onClick={()=>navigate('/',{replace:true})}><ArrowLeft/></button><strong>Rider Feed</strong><button type="button" disabled={busy} aria-label={text('Add video','Lisa video')} onClick={()=>input.current.click()}><Plus/></button><input hidden ref={input} type="file" accept="video/mp4,video/webm,video/quicktime" onChange={upload}/></header>
  {notice&&<div className="feed-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label={text('Close','Sulge')}>×</button></div>}
  <div className="feed-video-list" ref={viewport}>{posts.map(post=><article key={post.id} data-clip={post.id} className="feed-video-card">
   {post.poster&&<img className="feed-poster" src={post.poster} alt=""/>}
   <FeedVideo post={post} active={active===post.id} muted={muted} paused={paused} onPause={()=>setPaused(v=>!v)} onError={()=>setNotice(text('This video format could not be played.','Seda videovormingut ei saanud esitada.'))}/>
   <div className="feed-playback"><button type="button" aria-label={paused?text('Play','Esita'):text('Pause','Paus')} onClick={()=>setPaused(v=>!v)}>{paused?<Play/>:<Pause/>}</button><button type="button" aria-label={muted?text('Enable sound','Lülita heli sisse'):text('Mute','Vaigista')} onClick={()=>setMuted(v=>!v)}>{muted?<VolumeX/>:<Volume2/>}</button></div>
   <div className="feed-actions"><button type="button" aria-label={text('Like','Meeldib')} aria-pressed={!!social[post.id]?.liked} onClick={()=>setSocial(s=>({...s,[post.id]:{...s[post.id],liked:!s[post.id]?.liked}}))}><Heart fill={social[post.id]?.liked?'#f43f5e':'none'}/><span>{social[post.id]?.liked?1:0}</span></button><button type="button" aria-label={text('Comments','Kommentaarid')} onClick={()=>{setComments(post.id);setDraft('');}}><MessageCircle/><span>{social[post.id]?.comments?.length||0}</span></button>{post.local&&<button type="button" aria-label={text('Remove local video','Eemalda kohalik video')} onClick={async()=>{try{await removeFeedVideo(post.id);setLocalClips(clips=>clips.filter(c=>c.id!==post.id));setActive(FEATURED_VIDEOS[0].id);}catch{setNotice(text('Could not remove video.','Videot ei saanud eemaldada.'));}}}><Trash2/></button>}</div>
   <footer><strong>{post.author}</strong><p>{post.name}</p><span>{post.local?text('Your video · only on this device','Sinu video · ainult selles seadmes'):text('Real footage · edited excerpt','Päris video · lõigatud klipp')}</span>{post.source&&<details><summary>{text('Video source','Video allikas')}</summary><a href={post.source} target="_blank" rel="noreferrer">Made in Misha · {post.license}</a> · <a href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="noreferrer">{text('License','Litsents')}</a></details>}</footer>
  </article>)}</div>
  <nav className="feed-nav" aria-label={text('Video navigation','Videote vahetamine')}><button type="button" disabled={active===posts[0]?.id} aria-label={text('Previous video','Eelmine video')} onClick={()=>move(-1)}><ChevronUp/></button><span>{posts.findIndex(p=>p.id===active)+1} / {posts.length}</span><button type="button" disabled={active===posts.at(-1)?.id} aria-label={text('Next video','Järgmine video')} onClick={()=>move(1)}><ChevronDown/></button></nav>
  {comments&&<div className="feed-comments" role="dialog" aria-modal="true" aria-label={text('Comments','Kommentaarid')}><div><strong>{text('Comments','Kommentaarid')}</strong><button type="button" onClick={()=>setComments(null)} aria-label={text('Close comments','Sulge kommentaarid')}>×</button></div><p>{text('Saved on this device','Salvestatakse sellesse seadmesse')}</p><ul>{(social[comments]?.comments||[]).map((comment,i)=><li key={i}>{comment}</li>)}</ul><form onSubmit={e=>{e.preventDefault();if(!draft.trim())return;setSocial(s=>({...s,[comments]:{...s[comments],comments:[...(s[comments]?.comments||[]),draft.trim().slice(0,300)]}}));setDraft('');}}><input aria-label={text('Comment','Kommentaar')} maxLength={300} value={draft} onChange={e=>setDraft(e.target.value)}/><button type="submit" disabled={!draft.trim()}>{text('Add','Lisa')}</button></form></div>}
 </div>;
}
