import assert from 'node:assert/strict';
const saved=new Map(); globalThis.localStorage={getItem:k=>saved.get(k)??null,setItem:(k,v)=>saved.set(k,String(v)),removeItem:k=>saved.delete(k)};
const {VEHICLES,PARTS_CATALOG,SECRET_CODES}=await import('../src/lib/vehicleData.js');
const {getTires,saveTires,tireEffects,wearTires,newTraining,advanceTraining,scoreTraining,saveTrainingRecords,getTrainingRecords,compareBuildStats}=await import('../src/lib/rideUpgrades.js');
const {createStockBuild,calcBuildStats}=await import('../src/lib/buildState.js');
const {redeemSecretCode,getCodeRideModifiers}=await import('../src/lib/codeRewards.js');
const v=VEHICLES.find(v=>v.id==='g4'),b=createStockBuild(v.id),t=getTires(v,b);
assert.equal(tireEffects(v,t).grip,1);assert.equal(tireEffects(v,t).rolling,1);
const low={...t,frontPressure:.5};assert(tireEffects(v,low).grip<1);assert(tireEffects(v,low).rolling>1.5);
const worn={...t,frontWear:90,rearWear:80};assert(tireEffects(v,worn).grip<.7);
const more=wearTires(t,100,{throttle:1,brake:true});assert(more.frontWear>t.frontWear);assert(more.rearWear>t.rearWear);
saveTires(v.id,more);assert.equal(getTires(v,b).rearWear,more.rearWear);
assert.equal(getTires(v,{...b,parts:{wheel:{id:'new'}}}).rearWear,0);
let session=newTraining();session=advanceTraining(session,true,3);
const r1=scoreTraining(session,'normal',10),r2=scoreTraining(r1.state,'one-hand',25);assert.equal(r2.state.combo,2);assert.equal(r2.points,30);
assert.equal(scoreTraining(r2.state,'normal',10).points,0);
session=advanceTraining(r2.state,false,.1);assert.equal(session.combo,0);assert.equal(session.longestWheelie,3);
saveTrainingRecords(v.id,r2.state);saveTrainingRecords(v.id,newTraining());assert.equal(getTrainingRecords(v.id).bestCombo,2);
const base=compareBuildStats(calcBuildStats(v,b));
const cooler=PARTS_CATALOG.find(p=>p.category==='cooling'&&p.heatReduction>0);
assert(compareBuildStats(calcBuildStats(v,{...b,parts:{...b.parts,cooling:cooler}})).thermal<base.thermal);
const freshCodes=['FRESHTYRES','TIREGUARD','GRIPMASTER','ECOFLOW','COMBOKING','COOLPRO','BRAKEKING','REP10000'];
for(const code of freshCodes){assert(redeemSecretCode(code.toLowerCase()).success);assert(redeemSecretCode(code).duplicate);assert.equal(localStorage.getItem(SECRET_CODES[code].key),'true');}
assert.equal(getTires(v,b).rearWear,0);assert.equal(tireEffects(v,t).wearRate,.35);assert.equal(tireEffects(v,t).energy,.9);assert.equal(getCodeRideModifiers().heat,.6);assert.equal(getCodeRideModifiers().braking,1.3);
assert.equal(scoreTraining(newTraining(),'normal',10).points,15);
const master=redeemSecretCode('unlockall');assert(master.success);const respect=master.respect;assert(redeemSecretCode('UNLOCKALL').duplicate);assert.equal(Number(localStorage.getItem('kukirin_respect')),respect);
for(const entry of Object.values(SECRET_CODES))assert.equal(localStorage.getItem(entry.key),'true');
localStorage.setItem('kukirin_tires_g4','{"frontPressure":null,"frontWear":"NaN"}');assert.equal(getTires(v,b).frontPressure,3.2);
console.log('PASS v40: pressure/grip/rolling/wear, wheel replacement, combos/landing/records, cooling comparison, 8 real codes and idempotent UNLOCKALL.');
saved.clear();
const legacy=Object.keys(SECRET_CODES).filter(c=>!freshCodes.includes(c));
localStorage.setItem('kukirin_unlocked_codes',JSON.stringify(legacy));
for(const c of legacy)localStorage.setItem(SECRET_CODES[c].key,'true');
localStorage.setItem('kukirin_respect','123');
assert.equal(redeemSecretCode('UNLOCKALL').respect,10473);
assert.equal(redeemSecretCode('UNLOCKALL').respect,10473);
console.log('PASS v39 master save upgrades all 8 new codes once without repeating old rewards.');
