const {chromium}=require('C:/Users/sebas/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{if(location.protocol!=='http:')return;localStorage.setItem('kukirin_language','en');Math.random=()=>.1;});
const launch=async(size,training=true)=>{await page.setViewportSize(size);await page.goto('about:blank');await page.goto(`http://127.0.0.1:5173/#/telemetry/g2_2026?stock=1${training?'&practice=training':''}`);await page.getByRole('button',{name:/ENGAGE/}).click();await page.locator('.opaque-vehicle-photo[data-loaded="true"]').waitFor();await page.evaluate(()=>scrollTo(0,0));};
for(const size of [{width:360,height:640},{width:390,height:844},{width:412,height:915}])for(const training of [true,false]){
 await launch(size,training);const c=await page.locator('.ride-touch-console').boundingBox(),f=await page.locator('.ride-preview').boundingBox();assert(c.height<=145,'compact console');assert(f.y>=0&&f.y+f.height<=c.y,'whole preview above controls');assert.equal(await page.locator('.ride-control-button:visible').count(),3);assert.equal(await page.locator('.ride-trick-select option').count(),18);assert.equal(await page.locator('.ride-trick-picker button:visible').count(),0);assert.equal(await page.locator('.ride-steering button:visible').count(),0);assert.equal(await page.locator('.ride-metrics:visible').count(),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`../../outputs/v49-${size.width}-${training?'training':'ride'}.png`});
}
await launch({width:390,height:844});const gas=page.getByRole('button',{name:'GAS',exact:true}),wheel=page.getByRole('button',{name:'WHEELIE',exact:true}),brake=page.getByRole('button',{name:'Rear brake',exact:true});
const down=async(b,id)=>b.dispatchEvent('pointerdown',{pointerId:id,pointerType:'touch',buttons:1});const up=async(b,id)=>b.dispatchEvent('pointerup',{pointerId:id,pointerType:'touch'});
await down(gas,1);await down(gas,2);await page.waitForTimeout(300);assert.equal(await gas.getAttribute('aria-pressed'),'true');await up(gas,1);await gas.dispatchEvent('lostpointercapture',{pointerId:1});await page.waitForTimeout(150);assert.equal(await gas.getAttribute('aria-pressed'),'true','second finger must keep throttle held');await gas.dispatchEvent('pointercancel',{pointerId:2});await page.waitForTimeout(150);assert.equal(await gas.getAttribute('aria-pressed'),'false');
await down(gas,3);await page.waitForTimeout(300);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForTimeout(150);assert.equal(await gas.getAttribute('aria-pressed'),'false','blur must clear input and owners');
const select=page.getByRole('combobox',{name:'Wheelie trick'});await select.click();await page.keyboard.press('Escape');await select.selectOption('leg-wrap');assert.equal(await select.inputValue(),'leg-wrap');await select.focus();const before=Number(await page.locator('.ride-speed span').innerText());await page.keyboard.down('w');await page.waitForTimeout(300);await page.keyboard.up('w');assert(Number(await page.locator('.ride-speed span').innerText())<=before,'typing in selector cannot accelerate');
await down(gas,4);await page.waitForTimeout(1300);await up(gas,4);await wheel.focus();await page.keyboard.down('Space');await page.waitForFunction(()=>Number(document.querySelector('.ride-pitch')?.dataset.angle)>20);await page.keyboard.up('Space');await down(brake,5);await page.locator('.ride-photo-art:not(.is-wheelie)').waitFor();await up(brake,5);assert.equal(await wheel.getAttribute('aria-pressed'),'false');
await page.locator('.ride-control-options summary').click();assert(await page.getByRole('button',{name:'Body forward',exact:true}).isVisible());await page.locator('.ride-control-options summary').click();assert(!await page.getByRole('button',{name:'Body forward',exact:true}).isVisible());await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByRole('button',{name:/ENGAGE/}).waitFor();assert.equal(await page.locator('.ride-touch-console').count(),0);await page.getByRole('button',{name:/Back/}).click();await page.waitForURL(/#\/vehicle\/g2_2026/);assert.deepEqual(errors,[]);console.log('PASS compact 360/390/412 normal + training, 18 tricks, entire preview unobscured, two-finger throttle ownership/release/cancel/blur, no selector typing throttle, Space after focused hold button, rear brake, tools open/close, back navigation, no runtime errors.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
