import assert from 'node:assert/strict';
import { SECRET_CODES, VEHICLES } from '../src/lib/vehicleData.js';
import { redeemSecretCode, getUnlockedCodes, getCodeRideModifiers } from '../src/lib/codeRewards.js';
import { getTrickPoints } from '../src/lib/wheelieTricks.js';
const storage = new Map();
globalThis.localStorage = { getItem:key=>storage.get(key)??null, setItem:(key,value)=>storage.set(key,String(value)), removeItem:key=>storage.delete(key) };
assert.equal(redeemSecretCode('__proto__').success, false);
assert.equal(redeemSecretCode('constructor').success, false);
assert.equal(redeemSecretCode('unknown').success, false);
localStorage.setItem('kukirin_unlocked_codes', '{}');
localStorage.setItem('kukirin_respect', 'NaN');
assert.equal(redeemSecretCode(' rep5000 ').bonus, 5000);
assert.equal(redeemSecretCode('REP5000').duplicate, true);
assert.equal(Number(localStorage.getItem('kukirin_respect')), 5000);
localStorage.setItem('kukirin_broken_parts', '[{"part":"motor"}]');
const master = redeemSecretCode('unlockall');
assert(master.success);
assert.equal(getUnlockedCodes().length, Object.keys(SECRET_CODES).length);
for (const entry of Object.values(SECRET_CODES)) assert.equal(localStorage.getItem(entry.key),'true');
assert.equal(JSON.parse(localStorage.getItem('kukirin_vehicle_charge')).g4.pct,100);
assert.equal(Object.keys(JSON.parse(localStorage.getItem('kukirin_vehicle_charge'))).length,VEHICLES.length);
assert.equal(localStorage.getItem('kukirin_broken_parts'),'[]');
assert.deepEqual(getCodeRideModifiers(),{heat:.7,balance:120,trick:3,braking:1.2});
assert.equal(getTrickPoints('rocket'),270);
const respect = Number(localStorage.getItem('kukirin_respect'));
localStorage.setItem('kukirin_broken_parts','[{"part":"motor"}]');
localStorage.setItem('kukirin_vehicle_charge','{"g4":{"pct":25}}');
assert.equal(redeemSecretCode('UNLOCKALL').bonus,0);
assert.equal(Number(localStorage.getItem('kukirin_respect')),respect);
assert.equal(JSON.parse(localStorage.getItem('kukirin_vehicle_charge')).g4.pct,25);
assert.equal(JSON.parse(localStorage.getItem('kukirin_broken_parts')).length,1);
localStorage.removeItem(SECRET_CODES.BRAKEPRO.key);
assert(redeemSecretCode('UNLOCKALL').success);
assert.equal(Number(localStorage.getItem('kukirin_respect')),respect);
// An old master save must gain newly introduced codes, but never old REP again.
storage.clear();
const additions=['STUNTLEGEND','BALANCEPLUS','COOLMASTER','BRAKEPRO','REP5000','SERVICEALL'];
localStorage.setItem('kukirin_unlocked_codes',JSON.stringify(Object.keys(SECRET_CODES).filter(c=>!additions.includes(c))));
localStorage.setItem('kukirin_respect','12000');
assert.equal(redeemSecretCode('UNLOCKALL').bonus,5250);
assert.equal(Number(localStorage.getItem('kukirin_respect')),17250);
assert.equal(redeemSecretCode('UNLOCKALL').bonus,0);
// Newly installed catalog entries are discovered without a hard-coded master list.
SECRET_CODES.TESTUPDATE={key:'kukirin_test_update',respectBonus:123,reward:'test'};
assert.equal(redeemSecretCode('UNLOCKALL').bonus,123);
assert.equal(redeemSecretCode('UNLOCKALL').bonus,0);
delete SECRET_CODES.TESTUPDATE;
console.log('PASS: redemption, all flags, rewards, legacy master update, no repeat repairs/charge/REP, real ride modifiers');
