const {chromium}=require('C:/Users/sebas/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript(()=>{localStorage.setItem('kukirin_rider_name','QA');localStorage.setItem('kukirin_name_started','true');localStorage.setItem('kukirin_language','en');localStorage.setItem('kukirin_leaderboard_url','off');localStorage.setItem('kukirin_cloud_server_v60','true');localStorage.setItem('kukirin_unlock_wrapdrop','true');});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:5173')?r.continue():r.abort());
await page.goto('http://127.0.0.1:5173/#/build/g2_2026?tab=appearance');await page.getByRole('button',{name:'Wraps',exact:true}).click();
const canvas=page.locator('.tuning-showroom canvas.opaque-vehicle-photo');const sums={};for(const id of ['carbon_black','camo_green','galaxy_purple','chrome_silver','matte_black']){await page.getByLabel('Vinyl Wrap',{exact:true}).selectOption(id);await page.waitForFunction(id=>document.querySelector('.tuning-showroom canvas')?.dataset.wrap===id,id);sums[id]=await canvas.evaluate(c=>{const ctx=c.getContext('2d');const a=ctx.getImageData(0,0,c.width,c.height).data;let s=0;for(let i=0;i<a.length;i+=4)if(a[i+3])s+=a[i]+a[i+1]+a[i+2];return s;});if(['camo_green','carbon_black'].includes(id))await page.screenshot({path:'wrap-v62-'+id+'.png',fullPage:true});}assert.equal(new Set(Object.values(sums)).size,5);await page.reload();await page.getByRole('button',{name:'Wraps',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.tuning-showroom canvas')?.dataset.wrap==='matte_black');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
if(process.env.WRAP_ONLY){assert.deepEqual(errors,[]);console.log(sums);await browser.close();return;} const flows=await page.evaluate(async()=>{const {repairSteps}=await import('/src/components/RepairGame.jsx');return Object.fromEntries(['wheel','motor','battery','controller','chassis','damper','electronics'].map(p=>[p,repairSteps(p)]));});assert(flows.controller.findIndex(s=>s.id==='paste')<flows.controller.findIndex(s=>s.id==='install'));assert(flows.motor.find(s=>s.id==='phase1').tool==='hands');
async function begin(part){await page.evaluate(part=>{localStorage.setItem('kukirin_respect','1000');localStorage.setItem('kukirin_broken_parts',JSON.stringify([{part,vehicleId:'g2_2026',vehicleName:'G2 (2026)',code:'E-001'}]));},part);await page.goto('http://127.0.0.1:5173/#/repair');await page.reload();await page.getByRole('button',{name:/Repair \(/}).click();await page.getByRole('button',{name:'Inspect & start'}).click();await page.getByRole('button',{name:'Switch off & isolate'}).click();}
async function hold(point,ms){await point.scrollIntoViewIfNeeded();const b=await point.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.waitForTimeout(ms);await page.mouse.up();}
await begin('wheel');await page.locator('[data-tool=wrench]').click();await hold(page.locator('[data-point="0"]'),100);assert(await page.getByRole('button',{name:'Next step'}).isDisabled());await page.locator('[data-tool=hands]').click();await hold(page.locator('[data-point="0"]'),100);assert(await page.getByRole('button',{name:'Next step'}).isDisabled());await hold(page.locator('[data-point="0"]'),300);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForTimeout(800);assert(await page.getByRole('button',{name:'Next step'}).isDisabled());await page.getByLabel('Cancel repair',{exact:true}).click();assert.equal(await page.evaluate(()=>localStorage.getItem('kukirin_respect')),'1000');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('kukirin_broken_parts')).length),1);
for(const part of ['wheel','controller','chassis','motor','battery','damper','electronics']){await begin(part);for(const step of flows[part]){await page.locator(`[data-tool=${step.tool}]`).click();const range=page.locator('.repair-adjust input');const adjusting=await range.count();if(adjusting){await range.fill('0');await hold(page.locator('[data-point="0"]'),20);assert(await page.getByRole('button',{name:'Next step'}).isDisabled());await range.fill(step.tool==='hands'?'50':'70');}for(let n=0;n<step.count;n++){await hold(page.locator(`[data-point="${n}"]`),adjusting?40:step.tool==='welder'?1580:step.tool==='grinder'?1180:740);assert(await page.locator(`[data-point="${n}"]`).isDisabled());}assert(await page.getByRole('button',{name:'Next step'}).isEnabled());if(part==='controller'&&step.id==='screws'){await page.screenshot({path:'repair-v62-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await page.getByRole('button',{name:'Next step'}).click();}
assert(await page.getByRole('button',{name:'Finish inspection'}).isDisabled());for(let n=0;n<3;n++){await page.locator(`[data-check="${n}"]`).click();await page.waitForTimeout(930);}await page.getByRole('button',{name:'Finish inspection'}).click();await page.getByRole('button',{name:'Save repair & return'}).click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('kukirin_broken_parts')).length),0);assert(Number(await page.evaluate(()=>localStorage.getItem('kukirin_respect')))<1000);console.log('repair passed:',part);}
assert.deepEqual(errors,[]);console.log(JSON.stringify({wrapPixelSums:sums,flows:7,errors}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});

