const { chromium } = require('C:/Users/sebas/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:5173/#/city');
  await page.evaluate(() => { localStorage.setItem('kukirin_language','en'); localStorage.removeItem('kukirin_vehicle_charge'); });
  await page.reload();
  assert.equal(await page.getByRole('heading',{name:'City Ride'}).isVisible(), true);
  assert.equal(await page.getByRole('img',{name:'City map'}).isVisible(), true);
  assert.equal(await page.getByRole('button',{name:/Workshop Express/}).isVisible(), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({path:'../../outputs/v21-city-map-phone.png', fullPage:true});
  await page.clock.install();
  await page.getByRole('button',{name:/Workshop Express/}).click();
  await page.getByRole('button',{name:'GAS'}).dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch'});
  await page.clock.runFor(1300);
  await page.getByRole('button',{name:'GAS'}).dispatchEvent('pointerup',{pointerId:1,pointerType:'touch'});
  const speedText = await page.locator('.city-speed strong').innerText();
  assert(Number(speedText) > 0, 'Gas should accelerate');
  const initialLane = await page.locator('.city-rider').getAttribute('class');
  await page.getByRole('button',{name:/RIGHT/}).click();
  const changedLane = await page.locator('.city-rider').getAttribute('class');
  assert.notEqual(initialLane, changedLane);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({path:'../../outputs/v21-city-ride-phone.png'});
  await page.evaluate(() => window.dispatchEvent(new Event('kukirin:native-back')));
  await page.getByRole('heading',{name:'City Ride'}).waitFor();
  assert(await page.evaluate(() => JSON.parse(localStorage.getItem('kukirin_vehicle_charge')).g2_pro_2023.pct < 100));
  await page.getByRole('button',{name:/Workshop Express/}).click();
  await page.getByRole('button',{name:'GAS'}).dispatchEvent('pointerdown',{pointerId:2,pointerType:'touch'});
  await page.clock.runFor(140000);
  await page.getByText('MISSION COMPLETE').waitFor();
  await page.getByRole('button',{name:/Back to map/}).click();
  await page.evaluate(() => window.dispatchEvent(new Event('kukirin:native-back')));
  await page.waitForURL('**/#/');
  assert.deepEqual(errors, []);
  console.log(`PASS: city map, missions, acceleration (${speedText} km/h), lane change, battery persistence, mission completion, native back, phone overflow, no browser errors`);
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
