const { chromium } = require('C:/Users/sebas/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
 const { getVescMotorProfile } = await import('../src/lib/vescMotorProfile.js');
 const g2={id:'g2_2026',name:'G2',watts:800,voltage:48,tireSize:10,topSpeed:50};
 const g4={id:'g4',name:'G4',watts:2000,voltage:60,tireSize:11,topSpeed:65};
 const first=getVescMotorProfile(g2), second=getVescMotorProfile(g4);
 assert.deepEqual(first,getVescMotorProfile(g2),'repeat detection must be stable');
 assert.notEqual(first.r,second.r); assert.notEqual(first.kv,second.kv); assert.notEqual(first.poles,second.poles);
 assert.equal(getVescMotorProfile({...g2,vehicleType:'emoto'}).poles,10);
 assert.equal(getVescMotorProfile(g2,{parts:{motor:{id:'test',watts:5000,voltage:72,poles:20}}}).poles,20);
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function open(id) {
  await page.goto('http://127.0.0.1:5173/#/telemetry/'+id);
  await page.evaluate(id=>{localStorage.setItem('kukirin_language','en');const builds=JSON.parse(localStorage.getItem('kukirin_builds')||'{}');builds[id]={vehicleId:id,weldCount:0,frameExpansion:0,parts:{controller:{id:'vesc_test',name:'VESC',maxAmps:80,voltage:60,weight:1,tunable:true}},appearance:{},notes:[]};localStorage.setItem('kukirin_builds',JSON.stringify(builds));},id);
  await page.reload();await page.getByRole('button',{name:/ENGAGE/}).click();
  await page.getByText('Vehicle details',{exact:true}).click();
 }
 await open('g4');
 const tool=page.locator('.vesc-tool');
 await tool.getByRole('button',{name:'Detect',exact:true}).click();
 await tool.getByRole('button',{name:'Measure Motor Parameters'}).click();
 await tool.getByRole('button',{name:'Cancel',exact:true}).click();
 assert.equal(await tool.getByRole('button',{name:'Measure Motor Parameters'}).count(),1);
 await tool.getByRole('button',{name:'Measure Motor Parameters'}).click();
 await tool.getByRole('button',{name:'Apply detected parameters'}).click({timeout:16000});
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('kukirin_vesc_params_g4')));
 assert.equal(saved.motorPoles,40);assert.equal(saved.motorProfileId,'g4');assert(saved.motorResistance>0);
 await tool.getByRole('button',{name:'Info',exact:true}).click();
 assert((await tool.innerText()).includes('40 (20 pairs)'));
 await tool.getByRole('button',{name:'Motor',exact:true}).click();
 await tool.getByRole('spinbutton',{name:'Motor Poles value',exact:true}).fill('20');
 await tool.getByRole('button',{name:'Info',exact:true}).click();
 assert((await tool.innerText()).includes('20 (10 pairs)'));
 await tool.scrollIntoViewIfNeeded();
 assert(await tool.evaluate(e=>e.scrollWidth<=e.clientWidth+1),'VESC must fit phone width');
 await page.screenshot({path:'../../outputs/v31-vesc-mobile.png'});
 await open('g2_2026');
 await tool.getByRole('button',{name:'Detect',exact:true}).click();
 await tool.getByRole('button',{name:'Measure Motor Parameters'}).click();
 await tool.getByRole('button',{name:'Apply detected parameters'}).click({timeout:16000});
 const g2saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('kukirin_vesc_params_g2_2026')));
 assert.equal(g2saved.motorPoles,30);assert.notEqual(g2saved.motorResistance,saved.motorResistance);
 assert.deepEqual(errors,[]);
 console.log('PASS: model-specific stable profiles, cancellation, saved detection, editable poles, correct info, mobile width, no runtime errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
