const { chromium } = require('C:/Users/sebas/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({channel:'chrome',headless:true});
 const page = await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173/#/telemetry/g2_2026?stock=1');
 await page.evaluate(()=>localStorage.setItem('kukirin_language','en')); await page.reload();
 await page.getByRole('button',{name:/ENGAGE/}).click();
 await page.waitForFunction(()=>document.querySelector('.opaque-vehicle-photo')?.dataset.loaded==='true');
 assert.equal(await page.locator('.ride-photo-art').evaluate(e=>getComputedStyle(e).mixBlendMode),'normal');
 assert.equal(await page.locator('.photo-rider').count(),1);
 const gas=page.getByRole('button',{name:/GAS/}); const box=await gas.boundingBox();
 await page.mouse.move(box.x+20,box.y+20); await page.mouse.down(); await page.waitForTimeout(1500); await page.mouse.up();
 assert(Number(await page.locator('.ride-speed span').innerText())>0);
 await page.screenshot({path:'../../outputs/v30-rider.png'});
 await page.goto('http://127.0.0.1:5173/#/drag?career=alley_rookie&vehicle=s3_pro&opponent=ai_rookie');
 console.log(await page.getByRole('button').allTextContents());
 const start=page.getByRole('button',{name:/LINE UP/i}); await start.click();
 await page.getByRole('button',{name:/HOLD TO ACCELERATE/}).waitFor();
 const drag=await page.getByRole('button',{name:/HOLD TO ACCELERATE/}).boundingBox();
 await page.mouse.move(drag.x+30,drag.y+20); await page.mouse.down(); await page.mouse.move(drag.x+30,drag.y-15); await page.waitForTimeout(1500);
 await page.screenshot({path:'../../outputs/v30-career-gas.png'}); await page.mouse.up();
 assert((await page.locator('main').innerText()).includes('km/h'));
 await page.goto('http://127.0.0.1:5173/#/telemetry/g2_2026');
 await page.evaluate(()=>localStorage.setItem('kukirin_builds',JSON.stringify({g2_2026:{vehicleId:'g2_2026',weldCount:0,frameExpansion:0,parts:{controller:{id:'vesc_test',name:'VESC',maxAmps:80,voltage:48,weight:1,tunable:true}},appearance:{},notes:[]}})));
 await page.reload(); await page.getByRole('button',{name:/ENGAGE/}).click();
 await page.getByText('Vehicle details',{exact:true}).click();
 await page.locator('.vesc-tool').getByRole('button',{name:'Motor',exact:true}).click();
 await page.getByRole('spinbutton',{name:'Motor Current Max value',exact:true}).fill('0');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('kukirin_vesc_params_g2_2026')).motorCurrentMax),0);
 await page.getByText('Vehicle details',{exact:true}).click();
 const tunedGas=await page.getByRole('button',{name:/GAS/}).boundingBox();
 await page.mouse.move(tunedGas.x+20,tunedGas.y+20); await page.mouse.down(); await page.waitForTimeout(1000); await page.mouse.up();
 assert.equal(Number(await page.locator('.ride-speed span').innerText()),0,'zero motor current must stop acceleration');
 assert.deepEqual(errors,[]); console.log('PASS: opaque scooter, detailed rider, animated photo wheels, career pointer capture and no runtime errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
