const {chromium}=require('C:/Users/sebas/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
 const store={};global.localStorage={getItem:key=>store[key]||null};
 const {calcBuildStats,createStockBuild}=await import('../src/lib/buildState.js');
 const {VEHICLES,PARTS_CATALOG}=await import('../src/lib/vehicleData.js');
 const {solveRoadSpeed}=await import('../src/lib/drivePhysics.js');
 const {getVescMotorProfile}=await import('../src/lib/vescMotorProfile.js');
 const v=VEHICLES.find(v=>v.id==='g2_2026');const b=createStockBuild(v.id);
 const parts={motor:'hub_22000w_quantum',controller:'vesc_quantum_500d',battery:'pack_120v_50ah_solid',cooling:'cool_cryo_race',damper:'damper_hydraulic'};
 for(const [key,id] of Object.entries(parts))b.parts[key]=PARTS_CATALOG.find(p=>p.id===id);
 const upright=calcBuildStats(v,b);store.kukirin_rider_posture='tuck';const tucked=calcBuildStats(v,b);
 console.log({upright:upright.topSpeed,tucked:tucked.topSpeed,rpm:tucked.rpmLimitedSpeed});
 assert(tucked.topSpeed>140);assert(tucked.topSpeed>upright.topSpeed);
 assert.equal(calcBuildStats(v,createStockBuild(v.id)).topSpeed,v.topSpeed);
 const weak=structuredClone(b);weak.parts.controller.maxAmps=20;assert(calcBuildStats(v,weak).topSpeed<tucked.topSpeed);
 const slowWinding=structuredClone(b);slowWinding.parts.motor.kv=10;assert(calcBuildStats(v,slowWinding).topSpeed<tucked.topSpeed);
 const lowVoltage=structuredClone(b);lowVoltage.parts.battery.voltage=60;assert(calcBuildStats(v,lowVoltage).rpmLimitedSpeed<tucked.rpmLimitedSpeed);
 const gearing=structuredClone(b);gearing.parts.gearing={speedFactor:1.2,torqueFactor:1/1.2};assert(calcBuildStats(v,gearing).rpmLimitedSpeed>tucked.rpmLimitedSpeed);
 const stockGear=createStockBuild(v.id);stockGear.parts.gearing={speedFactor:.7,torqueFactor:1/.7};assert(calcBuildStats(v,stockGear).topSpeed<v.topSpeed);
 const other=calcBuildStats({...v,id:'other',topSpeed:20},b);assert.equal(other.motorKV,tucked.motorKV,'swapped winding must not depend on donor speed');
 assert.equal(getVescMotorProfile(v,b).kv,tucked.motorKV);
 assert(solveRoadSpeed(150000,150,.34)>230,'numerical solver must not impose a 230 km/h cap');
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.clock.install();await page.addInitScript(()=>{Math.random=()=>.1;});
 await page.goto('http://127.0.0.1:5173/#/telemetry/g2_2026');
 await page.evaluate(b=>{localStorage.setItem('kukirin_language','en');localStorage.setItem('kukirin_game_settings',JSON.stringify({damageEnabled:false}));localStorage.setItem('kukirin_builds',JSON.stringify({g2_2026:b}));localStorage.removeItem('kukirin_vesc_params_g2_2026');localStorage.removeItem('kukirin_rider_posture');},b);await page.reload();
 await page.evaluate(()=>{const schedule=setTimeout;window.setTimeout=(fn,delay,...args)=>schedule(fn,delay>20000&&delay<50000?3600000:delay,...args);});
 await page.getByRole('button',{name:/ENGAGE/}).click();
 await page.getByRole('button',{name:'Upright',exact:true}).click();
 assert((await page.locator('.ride-speed-envelope').innerText()).includes('159'));
 await page.keyboard.down('w');await page.clock.runFor(120000);await page.keyboard.up('w');
 const speed=Number(await page.locator('.ride-speed span').innerText());console.log('Driven speed:',speed,'km/h');assert(speed>140,'strong tuned build must be able to pass 140 in Drive');
 await page.screenshot({path:'../../outputs/v33-speed.png'});
 await page.getByText('Vehicle details',{exact:true}).click();await page.locator('.vesc-tool').getByRole('button',{name:'Motor',exact:true}).click();
 await page.getByRole('spinbutton',{name:'Motor Current Max value',exact:true}).fill('80');
 await page.getByRole('button',{name:'Use build current limits',exact:true}).click();
 assert.equal(await page.getByRole('spinbutton',{name:'Motor Current Max value',exact:true}).inputValue(),'500');
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: no shared speed cap, donor-independent winding, voltage/current/gearing/posture limits, actual ride above 140, current reset');
})().catch(e=>{console.error(e);process.exit(1);});
