CREATE TABLE IF NOT EXISTS scores(id TEXT PRIMARY KEY,name TEXT NOT NULL,mode TEXT NOT NULL,value REAL NOT NULL,vehicle TEXT NOT NULL,time INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS scores_mode ON scores(mode);
